application: mol-api
version: point-uploads
runtime: python27
threadsafe: true
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: loader_app/static
- url: /templates
  static_dir: templates
- url: /uploads
  static_dir: uploads

- url: .*
  script: loader_app.app

libraries:
- name: pycrypto
  version: "2.3"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"


