application: map-of-life
version: beta
runtime: python27
threadsafe: true
api_version: 1

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /static
  static_dir: loader_app/static
  secure: always
- url: /templates
  static_dir: templates
  secure: always
- url: /uploads
  static_dir: uploads
  secure: always

# APIs
- url: /api/species.*
  script: loader_app.services.loader.species
  secure: always

- url: /api/title.*
  script: loader_app.services.loader.title
  secure: always

- url: /api/mapAvailable.*
  script: loader_app.services.loader.mapAvailable
  secure: always

- url: /api/points.*
  script: loader_app.services.loader.points
  secure: always


- url: .*
  script: loader_app.app
  secure: always

libraries:
- name: pycrypto
  version: "2.3"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"


