__author__ = '@jotegui'

dwc_terms = {
    'Record': {
        'type': {'url': 'http://purl.org/dc/terms/type', 'def': ''},    
        'modified': {'url': 'http://purl.org/dc/terms/modified', 'def': ''},
        'language': {'url': 'http://purl.org/dc/terms/language', 'def': ''},
        'rights': {'url': 'http://purl.org/dc/terms/rights', 'def': ''},
        'rightsHolder': {'url': 'http://purl.org/dc/terms/rightsHolder', 'def': ''},
        'accessRights': {'url': 'http://purl.org/dc/terms/accessRights', 'def': ''},
        'bibliographicCitation': {'url': 'http://purl.org/dc/terms/bibliographicCitation', 'def': ''},
        'references': {'url': 'http://purl.org/dc/terms/references', 'def': ''},
        'institutionID': {'url': 'http://rs.tdwg.org/dwc/terms/institutionID', 'def': ''},
        'collectionID': {'url': 'http://rs.tdwg.org/dwc/terms/collectionID', 'def': ''},
        'datasetID': {'url': 'http://rs.tdwg.org/dwc/terms/datasetID', 'def': ''},
        'institutionCode': {'url': 'http://rs.tdwg.org/dwc/terms/institutionCode', 'def': ''},
        'collectionCode': {'url': 'http://rs.tdwg.org/dwc/terms/collectionCode', 'def': ''},
        'datasetName': {'url': 'http://rs.tdwg.org/dwc/terms/datasetName', 'def': ''},
        'ownerInstitutionCode': {'url': 'http://rs.tdwg.org/dwc/terms/ownerInstitutionCode', 'def': ''},
        'basisOfRecord': {'url': 'http://rs.tdwg.org/dwc/terms/basisOfRecord', 'def': 'Nature of the record: Human Observation, Preserved Specimen...'},
        'informationWithheld': {'url': 'http://rs.tdwg.org/dwc/terms/informationWithheld', 'def': ''},
        'dataGeneralizations': {'url': 'http://rs.tdwg.org/dwc/terms/dataGeneralizations', 'def': ''},
        'dynamicProperties': {'url': 'http://rs.tdwg.org/dwc/terms/dynamicProperties', 'def': ''}
    },
    'Occurrence': {
        'occurrenceID': {'url': 'http://rs.tdwg.org/dwc/terms/occurrenceID', 'def': ''},
        'catalogNumber': {'url': 'http://rs.tdwg.org/dwc/terms/catalogNumber', 'def': ''},
        'occurrenceRemarks': {'url': 'http://rs.tdwg.org/dwc/terms/occurrenceRemarks', 'def': ''},
        'recordNumber': {'url': 'http://rs.tdwg.org/dwc/terms/recordNumber', 'def': ''},
        'recordedBy': {'url': 'http://rs.tdwg.org/dwc/terms/recordedBy', 'def': ''},
        'individualID': {'url': 'http://rs.tdwg.org/dwc/terms/individualID', 'def': ''},
        'individualCount': {'url': 'http://rs.tdwg.org/dwc/terms/individualCount', 'def': ''},
        'sex': {'url': 'http://rs.tdwg.org/dwc/terms/sex', 'def': ''},
        'lifeStage': {'url': 'http://rs.tdwg.org/dwc/terms/lifeStage', 'def': ''},
        'reproductiveCondition': {'url': 'http://rs.tdwg.org/dwc/terms/reproductiveCondition', 'def': ''},
        'behavior': {'url': 'http://rs.tdwg.org/dwc/terms/behavior', 'def': ''},
        'establishmentMeans': {'url': 'http://rs.tdwg.org/dwc/terms/establishmentMeans', 'def': ''},
        'occurrenceStatus': {'url': 'http://rs.tdwg.org/dwc/terms/occurrenceStatus', 'def': ''},
        'preparations': {'url': 'http://rs.tdwg.org/dwc/terms/preparations', 'def': ''},
        'disposition': {'url': 'http://rs.tdwg.org/dwc/terms/disposition', 'def': ''},
        'otherCatalogNumbers': {'url': 'http://rs.tdwg.org/dwc/terms/otherCatalogNumbers', 'def': ''},
        'previousIdentifications': {'url': 'http://rs.tdwg.org/dwc/terms/previousIdentifications', 'def': ''},
        'associatedMedia': {'url': 'http://rs.tdwg.org/dwc/terms/associatedMedia', 'def': ''},
        'associatedReferences': {'url': 'http://rs.tdwg.org/dwc/terms/associatedReferences', 'def': ''},
        'associatedOccurrences': {'url': 'http://rs.tdwg.org/dwc/terms/associatedOccurrences', 'def': ''},
        'associatedSequences': {'url': 'http://rs.tdwg.org/dwc/terms/associatedSequences', 'def': ''},
        'associatedTaxa': {'url': 'http://rs.tdwg.org/dwc/terms/associatedTaxa', 'def': ''}
    },
    'MaterialSample': {
        'materialSampleId': {'url': 'http://rs.tdwg.org/dwc/terms/materialSampleID', 'def': ''}
    },
    'Event': {
        'eventID': {'url': 'http://rs.tdwg.org/dwc/terms/eventID', 'def': ''},    
        'samplingProtocol': {'url': 'http://rs.tdwg.org/dwc/terms/samplingProtocol', 'def': ''},
        'samplingEffort': {'url': 'http://rs.tdwg.org/dwc/terms/samplingEffort', 'def': ''},
        'eventDate': {'url': 'http://rs.tdwg.org/dwc/terms/eventDate', 'def': ''},
        'eventTime': {'url': 'http://rs.tdwg.org/dwc/terms/eventTime', 'def': ''},
        'startDayOfYear': {'url': 'http://rs.tdwg.org/dwc/terms/startDayOfYear', 'def': ''},
        'endDayOfYear': {'url': 'http://rs.tdwg.org/dwc/terms/endDayOfYear', 'def': ''},
        'year': {'url': 'http://rs.tdwg.org/dwc/terms/year', 'def': ''},
        'month': {'url': 'http://rs.tdwg.org/dwc/terms/month', 'def': ''},
        'day': {'url': 'http://rs.tdwg.org/dwc/terms/day', 'def': ''},
        'verbatimEventDate': {'url': 'http://rs.tdwg.org/dwc/terms/verbatimEventDate', 'def': ''},
        'habitat': {'url': 'http://rs.tdwg.org/dwc/terms/habitat', 'def': ''},
        'fieldNumber': {'url': 'http://rs.tdwg.org/dwc/terms/fieldNumber', 'def': ''},
        'fieldNotes': {'url': 'http://rs.tdwg.org/dwc/terms/fieldNotes', 'def': ''},
        'eventRemarks': {'url': 'http://rs.tdwg.org/dwc/terms/eventRemarks', 'def': ''}
    },
    'Location': {
        'locationID': {'url': 'http://rs.tdwg.org/dwc/terms/locationID', 'def': ''},
        'higherGeographyID': {'url': 'http://rs.tdwg.org/dwc/terms/higherGeographyID', 'def': ''},
        'higherGeography': {'url': 'http://rs.tdwg.org/dwc/terms/higherGeography', 'def': ''},
        'continent': {'url': 'http://rs.tdwg.org/dwc/terms/continent', 'def': ''},
        'waterBody': {'url': 'http://rs.tdwg.org/dwc/terms/waterBody', 'def': ''},
        'islandGroup': {'url': 'http://rs.tdwg.org/dwc/terms/islandGroup', 'def': ''},
        'island': {'url': 'http://rs.tdwg.org/dwc/terms/island', 'def': ''},
        'country': {'url': 'http://rs.tdwg.org/dwc/terms/country', 'def': ''},
        'countryCode': {'url': 'http://rs.tdwg.org/dwc/terms/countryCode', 'def': ''},
        'stateProvince': {'url': 'http://rs.tdwg.org/dwc/terms/stateProvince', 'def': ''},
        'county': {'url': 'http://rs.tdwg.org/dwc/terms/county', 'def': ''},
        'municipality': {'url': 'http://rs.tdwg.org/dwc/terms/municipality', 'def': ''},
        'locality': {'url': 'http://rs.tdwg.org/dwc/terms/locality', 'def': ''},
        'verbatimLocality': {'url': 'http://rs.tdwg.org/dwc/terms/verbatimLocality', 'def': ''},
        'verbatimElevation': {'url': 'http://rs.tdwg.org/dwc/terms/verbatimElevation', 'def': ''},
        'minimumElevationInMeters': {'url': 'http://rs.tdwg.org/dwc/terms/minimumElevationInMeters', 'def': ''},
        'maximumElevationInMeters': {'url': 'http://rs.tdwg.org/dwc/terms/maximumElevationInMeters', 'def': ''},
        'verbatimDepth': {'url': 'http://rs.tdwg.org/dwc/terms/verbatimDepth', 'def': ''},
        'minimumDepthInMeters': {'url': 'http://rs.tdwg.org/dwc/terms/minimumDepthInMeters', 'def': ''},
        'maximumDepthInMeters': {'url': 'http://rs.tdwg.org/dwc/terms/maximumDepthInMeters', 'def': ''},
        'minimumDistanceAboveSurfaceInMeters': {'url': 'http://rs.tdwg.org/dwc/terms/minimumDistanceAboveSurfaceInMeters', 'def': ''},
        'maximumDistanceAboveSurfaceInMeters': {'url': 'http://rs.tdwg.org/dwc/terms/maximumDistanceAboveSurfaceInMeters', 'def': ''},
        'locationAccordingTo': {'url': 'http://rs.tdwg.org/dwc/terms/locationAccordingTo', 'def': ''},
        'locationRemarks': {'url': 'http://rs.tdwg.org/dwc/terms/locationRemarks', 'def': ''},
        'verbatimCoordinates': {'url': 'http://rs.tdwg.org/dwc/terms/verbatimCoordinates', 'def': ''},
        'verbatimLatitude': {'url': 'http://rs.tdwg.org/dwc/terms/verbatimLatitude', 'def': ''},
        'verbatimLongitude': {'url': 'http://rs.tdwg.org/dwc/terms/verbatimLongitude', 'def': ''},
        'verbatimCoordinateSystem': {'url': 'http://rs.tdwg.org/dwc/terms/verbatimCoordinateSystem', 'def': ''},
        'verbatimSRS': {'url': 'http://rs.tdwg.org/dwc/terms/verbatimSRS', 'def': ''},
        'decimalLatitude': {'url': 'http://rs.tdwg.org/dwc/terms/decimalLatitude', 'def': ''},
        'decimalLongitude': {'url': 'http://rs.tdwg.org/dwc/terms/decimalLongitude', 'def': ''},
        'geodeticDatum': {'url': 'http://rs.tdwg.org/dwc/terms/geodeticDatum', 'def': ''},
        'coordinateUncertaintyInMeters': {'url': 'http://rs.tdwg.org/dwc/terms/coordinateUncertaintyInMeters', 'def': ''},
        'coordinatePrecision': {'url': 'http://rs.tdwg.org/dwc/terms/coordinatePrecision', 'def': ''},
        'pointRadiusSpatialFit': {'url': 'http://rs.tdwg.org/dwc/terms/pointRadiusSpatialFit', 'def': ''},
        'footprintWKT': {'url': 'http://rs.tdwg.org/dwc/terms/footprintWKT', 'def': ''},
        'footprintSRS': {'url': 'http://rs.tdwg.org/dwc/terms/footprintSRS', 'def': ''},
        'footprintSpatialFit': {'url': 'http://rs.tdwg.org/dwc/terms/footprintSpatialFit', 'def': ''},
        'georeferencedBy': {'url': 'http://rs.tdwg.org/dwc/terms/georeferencedBy', 'def': ''},
        'georeferencedDate': {'url': 'http://rs.tdwg.org/dwc/terms/georeferencedDate', 'def': ''},
        'georeferenceProtocol': {'url': 'http://rs.tdwg.org/dwc/terms/georeferenceProtocol', 'def': ''},
        'georeferenceSources': {'url': 'http://rs.tdwg.org/dwc/terms/georeferenceSources', 'def': ''},
        'georeferenceVerificationStatus': {'url': 'http://rs.tdwg.org/dwc/terms/georeferenceVerificationStatus', 'def': ''},
        'georeferenceRemarks': {'url': 'http://rs.tdwg.org/dwc/terms/georeferenceRemarks', 'def': ''}
    },
    'GeologicalContext': {
        'geologicalContextID': {'url': 'http://rs.tdwg.org/dwc/terms/geologicalContextID', 'def': ''},    
        'earliestEonOrLowestEonothem': {'url': 'http://rs.tdwg.org/dwc/terms/earliestEonOrLowestEonothem', 'def': ''},
        'latestEonOrHighestEonothem': {'url': 'http://rs.tdwg.org/dwc/terms/latestEonOrHighestEonothem', 'def': ''},
        'earliestEraOrLowestErathem': {'url': 'http://rs.tdwg.org/dwc/terms/earliestEraOrLowestErathem', 'def': ''},
        'latestEraOrHighestErathem': {'url': 'http://rs.tdwg.org/dwc/terms/latestEraOrHighestErathem', 'def': ''},
        'earliestPeriodOrLowestSystem': {'url': 'http://rs.tdwg.org/dwc/terms/earliestPeriodOrLowestSystem', 'def': ''},
        'latestPeriodOrHighestSystem': {'url': 'http://rs.tdwg.org/dwc/terms/latestPeriodOrHighestSystem', 'def': ''},
        'earliestEpochOrLowestSeries': {'url': 'http://rs.tdwg.org/dwc/terms/earliestEpochOrLowestSeries', 'def': ''},
        'latestEpochOrHighestSeries': {'url': 'http://rs.tdwg.org/dwc/terms/latestEpochOrHighestSeries', 'def': ''},
        'earliestAgeOrLowestStage': {'url': 'http://rs.tdwg.org/dwc/terms/earliestAgeOrLowestStage', 'def': ''},
        'latestAgeOrHighestStage': {'url': 'http://rs.tdwg.org/dwc/terms/latestAgeOrHighestStage', 'def': ''},
        'lowestBiostratigraphicZone': {'url': 'http://rs.tdwg.org/dwc/terms/lowestBiostratigraphicZone', 'def': ''},
        'highestBiostratigraphicZone': {'url': 'http://rs.tdwg.org/dwc/terms/highestBiostratigraphicZone', 'def': ''},
        'lithostratigraphicTerms': {'url': 'http://rs.tdwg.org/dwc/terms/lithostratigraphicTerms', 'def': ''},
        'group': {'url': 'http://rs.tdwg.org/dwc/terms/group', 'def': ''},
        'formation': {'url': 'http://rs.tdwg.org/dwc/terms/formation', 'def': ''},
        'member': {'url': 'http://rs.tdwg.org/dwc/terms/member', 'def': ''},
        'bed': {'url': 'http://rs.tdwg.org/dwc/terms/bed', 'def': ''}
    },
    'Identification': {
        'identificationID': {'url': 'http://rs.tdwg.org/dwc/terms/identificationID', 'def': ''},
        'identifiedBy': {'url': 'http://rs.tdwg.org/dwc/terms/identifiedBy', 'def': ''},
        'dateIdentified': {'url': 'http://rs.tdwg.org/dwc/terms/dateIdentified', 'def': ''},
        'identificationReferences': {'url': 'http://rs.tdwg.org/dwc/terms/identificationReferences', 'def': ''},
        'identificationVerificationStatus': {'url': 'http://rs.tdwg.org/dwc/terms/identificationVerificationStatus', 'def': ''},
        'identificationRemarks': {'url': 'http://rs.tdwg.org/dwc/terms/identificationRemarks', 'def': ''},
        'identificationQualifier': {'url': 'http://rs.tdwg.org/dwc/terms/identificationQualifier', 'def': ''},
        'typeStatus': {'url': 'http://rs.tdwg.org/dwc/terms/typeStatus', 'def': ''}
    },
    'Taxon': {
        'taxonID': {'url': 'http://rs.tdwg.org/dwc/terms/taxonID', 'def': ''},
        'scientificNameID': {'url': 'http://rs.tdwg.org/dwc/terms/scientificNameID', 'def': ''},
        'acceptedNameUsageID': {'url': 'http://rs.tdwg.org/dwc/terms/acceptedNameUsageID', 'def': ''},
        'parentNameUsageID': {'url': 'http://rs.tdwg.org/dwc/terms/parentNameUsageID', 'def': ''},
        'originalNameUsageID': {'url': 'http://rs.tdwg.org/dwc/terms/originalNameUsageID', 'def': ''},
        'nameAccordingToID': {'url': 'http://rs.tdwg.org/dwc/terms/nameAccordingToID', 'def': ''},
        'namePublishedInID': {'url': 'http://rs.tdwg.org/dwc/terms/namePublishedInID', 'def': ''},
        'taxonConceptID': {'url': 'http://rs.tdwg.org/dwc/terms/taxonConceptID', 'def': ''},
        'scientificName': {'url': 'http://rs.tdwg.org/dwc/terms/scientificName', 'def': ''},
        'acceptedNameUsage': {'url': 'http://rs.tdwg.org/dwc/terms/acceptedNameUsage', 'def': ''},
        'parentNameUsage': {'url': 'http://rs.tdwg.org/dwc/terms/parentNameUsage', 'def': ''},
        'originalNameUsage': {'url': 'http://rs.tdwg.org/dwc/terms/originalNameUsage', 'def': ''},
        'nameAccordingTo': {'url': 'http://rs.tdwg.org/dwc/terms/nameAccordingTo', 'def': ''},
        'namePublishedIn': {'url': 'http://rs.tdwg.org/dwc/terms/namePublishedIn', 'def': ''},
        'namePublishedInYear': {'url': 'http://rs.tdwg.org/dwc/terms/namePublishedInYear', 'def': ''},
        'higherClassification': {'url': 'http://rs.tdwg.org/dwc/terms/higherClassification', 'def': ''},
        'kingdom': {'url': 'http://rs.tdwg.org/dwc/terms/kingdom', 'def': ''},
        'phylum': {'url': 'http://rs.tdwg.org/dwc/terms/phylum', 'def': ''},
        'class': {'url': 'http://rs.tdwg.org/dwc/terms/class', 'def': ''},
        'order': {'url': 'http://rs.tdwg.org/dwc/terms/order', 'def': ''},
        'family': {'url': 'http://rs.tdwg.org/dwc/terms/family', 'def': ''},
        'genus': {'url': 'http://rs.tdwg.org/dwc/terms/genus', 'def': ''},
        'subgenus': {'url': 'http://rs.tdwg.org/dwc/terms/subgenus', 'def': ''},
        'specificEpithet': {'url': 'http://rs.tdwg.org/dwc/terms/specificEpithet', 'def': ''},
        'infraspecificEpithet': {'url': 'http://rs.tdwg.org/dwc/terms/infraspecificEpithet', 'def': ''},
        'taxonRank': {'url': 'http://rs.tdwg.org/dwc/terms/taxonRank', 'def': ''},
        'verbatimTaxonRank': {'url': 'http://rs.tdwg.org/dwc/terms/verbatimTaxonRank', 'def': ''},
        'scientificNameAuthorship': {'url': 'http://rs.tdwg.org/dwc/terms/scientificNameAuthorship', 'def': ''},
        'vernacularName': {'url': 'http://rs.tdwg.org/dwc/terms/vernacularName', 'def': ''},
        'nomenclaturalCode': {'url': 'http://rs.tdwg.org/dwc/terms/nomenclaturalCode', 'def': ''},
        'taxonomicStatus': {'url': 'http://rs.tdwg.org/dwc/terms/taxonomicStatus', 'def': ''},
        'nomenclaturalStatus': {'url': 'http://rs.tdwg.org/dwc/terms/nomenclaturalStatus', 'def': ''},
        'taxonRemarks': {'url': 'http://rs.tdwg.org/dwc/terms/taxonRemarks', 'def': ''}
    }
}
